name: Quinn Michaels
title: Quinn's Singing Bowl Studio
describe: Discover the transformative power of sound therapy with Quinn Michaels. Explore our curated collection of crystal and Tibetan singing bowls, designed to promote relaxation, meditation, and healing.
image: /assets/headers/001-temple.jpg
author: Quinn Michaels
copyright: (c)2024 Quinn Michaels. All rights reserved.
