name: Quinn Michaels
title: Quinn Michaels
describe: Discover the transformative power of sound therapy with Quinn Michaels. Explore our curated collection of crystal and Tibetan singing bowls, designed to promote relaxation, meditation, and healing.
image: /assets/headers/001-temple.jpg
author: Quinn Michaels
copyright: (c)2024 Quinn Michaels. All rights reserved.
xcreator: quinnmichaels
xsite: quinnmichaels
collections:
  posts:
    output: true
    permalink: /blog/:name
  art:
    output: true
    permalink: /:collection/:name
  bowls:
    output: true
    permalink: /:collection/:name
  videos:
    output: true
    permalink: /:collection/:name
